version: '3'
services:
  roles_test:
      build:
          context: .
          dockerfile: Dockerfile-test
      working_dir: /rbac
      entrypoint: 'tox -r'
      environment:
        - POSTGRES_SQL_SERVICE_HOST=db
        - POSTGRES_SQL_SERVICE_PORT=5432
      volumes:
        - '.:/rbac/'
      links:
        - db

  db:
    image: postgres:9.6
    environment:
    - POSTGRES_DB=rbac_test
    - POSTGRES_USER=postgres
    ports:
      - "15433:5432"
    volumes:
      - ./pg_data:/var/lib/pgsql/data
