apiVersion: v1
kind: Template
labels:
  app: rbac
  template: rbac
metadata:
  annotations:
    description: Role Based Access Control powered by Django+PostgreSQL
    iconClass: icon-python
    openshift.io/display-name: rbac-pgsql
    openshift.io/documentation-url: https://insight-rbac.readthedocs.io/en/latest/
    openshift.io/long-description: This template defines resources needed to run the
      RBAC application database
    openshift.io/provider-display-name: Red Hat, Inc.
    tags: quickstart,python,django,postgresql
  name: rbac
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: rbac
      template: rbac
    name: rbac-pgsql
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{DB_REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        name: rbac-pgsql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: rbac
          name: rbac-pgsql
          template: rbac
        name: rbac-pgsql
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rbac
                  - key: template
                    operator: In
                    values:
                    - rbac
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rbac
                  - key: template
                    operator: In
                    values:
                    - rbac
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                key: db.user
                name: ${DB_SECRET_NAME}
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db.password
                name: ${DB_SECRET_NAME}
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: db.name
                name: ${DB_SECRET_NAME}
          image: registry.redhat.io/rhel8/postgresql-96
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - /usr/libexec/check-container
              - --live
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: rbac-pgsql
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /usr/libexec/check-container
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: rbac-pgsql-data
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        volumes:
        - name: rbac-pgsql-data
          persistentVolumeClaim:
            claimName: rbac-pgsql
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: rbac
      template: rbac
    name: rbac-pgsql
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the database server
    labels:
      app: rbac
      template: rbac
    name: rbac-pgsql
  spec:
    ports:
    - name: rbac-pgsql
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: ${SERVICE_DEPENDENCY_NAME}
parameters:
- description: Initial amount of memory
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 512Mi
- description: Maximum amount of memory
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: Initial amount of cpu
  displayName: CPU Request
  name: CPU_REQUEST
  required: true
  value: 300m
- description: Maximum amount of cpu
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: '1'
- description: Volume space available for data, e.g. 512Mi, 2Gi
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- displayName: Service Dependency Name
  name: SERVICE_DEPENDENCY_NAME
  value: rbac-pgsql
- description: The number of replicas to be used by the DB
  displayName: DB Replicas
  name: DB_REPLICAS
  value: '0'
- description: Name of DB secret
  name: DB_SECRET_NAME
  value: rbac-db
