apiVersion: v1
kind: Template
labels:
  app: ${NAME}
  template: ${NAME}-scheduler
metadata:
  annotations:
    description: Scheduler for Role Based Access Control powered by Django+PostgreSQL+Celery
    iconClass: icon-python
    openshift.io/display-name: RBAC
    openshift.io/documentation-url: https://insight-rbac.readthedocs.io/en/latest/
    openshift.io/long-description: This template defines resources needed to run the
      RBAC application, including a build configuration, application deployment configuration,
      and database deployment configuration.
    openshift.io/provider-display-name: Red Hat, Inc.
    tags: python,flask
  name: rbac-scheduler
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}-scheduler
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        name: ${NAME}-scheduler
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}-scheduler
        name: ${NAME}-scheduler
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: name
                    operator: In
                    values:
                    - ${NAME}-scheduler
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: name
                    operator: In
                    values:
                    - ${NAME}-scheduler
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - command:
          - /bin/bash
          - -c
          - 'PYTHONPATH=${PWD}/rbac/ celery -A rbac.celery beat -l $DJANGO_LOG_LEVEL

            '
          env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                key: redis-service-host
                name: redis-config
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                key: redis-service-port
                name: redis-config
          - name: DJANGO_LOG_LEVEL
            value: ${DJANGO_LOG_LEVEL}
          - name: DJANGO_DEBUG
            value: ${DJANGO_DEBUG}
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PERMISSION_SEEDING_ENABLED
            value: 'False'
          - name: ROLE_SEEDING_ENABLED
            value: 'False'
          - name: GROUP_SEEDING_ENABLED
            value: 'False'
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          image: quay.io/cloudservices/rbac:${IMAGE_TAG}
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - 'PYTHONPATH=${PWD}/rbac/ celery inspect ping -A rbac.celery

                '
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 10
          name: ${NAME}-scheduler
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - 'PYTHONPATH=${PWD}/rbac/ celery inspect ping -A rbac.celery

                '
            failureThreshold: 3
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: ${CELERY_SCHEDULER_CPU_LIMIT}
              memory: ${CELERY_SCHEDULER_MEMORY_LIMIT}
            requests:
              cpu: ${CELERY_SCHEDULER_CPU_REQUEST}
              memory: ${CELERY_SCHEDULER_MEMORY_REQUEST}
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
parameters:
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: rbac
- description: Initial amount of CPU the Flower container will request.
  displayName: Celery scheduler CPU Resource Request
  name: CELERY_SCHEDULER_CPU_REQUEST
  required: true
  value: 100m
- description: Maximum amount of CPU the scheduler container can use.
  displayName: CPU Limit
  name: CELERY_SCHEDULER_CPU_LIMIT
  required: true
  value: 300m
- description: Initial amount of memory the scheduler container will request.
  displayName: Celery scheduler Memory Resource Request
  name: CELERY_SCHEDULER_MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory the scheduler container can use.
  displayName: Memory Limit
  name: CELERY_SCHEDULER_MEMORY_LIMIT
  required: true
  value: 512Mi
- displayName: Django Debug
  name: DJANGO_DEBUG
  value: 'false'
- displayName: Django log level
  name: DJANGO_LOG_LEVEL
  value: INFO
- description: The number of replicas to use for the prometheus deployment
  name: REPLICAS
  value: '1'
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: 'false'
- description: Image tag
  name: IMAGE_TAG
  required: true
